"""empty message

Revision ID: 0053a8c58708
Revises: 1f26c35dec03
Create Date: 2023-01-27 09:42:58.083328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0053a8c58708'
down_revision = '1f26c35dec03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_x_vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'character_x_vehicle', ['character_x_vehicle_id'], ['id'])

    with op.batch_alter_table('character_x_vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('character_x_vehicle_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('character_x_vehicle_character_id_fkey', type_='foreignkey')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_x_vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'character_x_vehicle', ['character_x_vehicle_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('character_x_vehicle_id')

    with op.batch_alter_table('character_x_vehicle', schema=None) as batch_op:
        batch_op.create_foreign_key('character_x_vehicle_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.create_foreign_key('character_x_vehicle_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('character_x_vehicle_id')

    # ### end Alembic commands ###
